image: Visual Studio 2017

branches:
  only:
    - s_4_hometask_8

before_build:
  - dotnet restore semester_4/hometask_8/hometask_8.sln

test_script:
  - dotnet test semester_4/hometask_8/hometask_8.sln

build:
project: semester_4/hometask_8/hometask_8.sln