image: Visual Studio 2017

branches:
  only:
    - s_4_hometask_2

before_build:
  - nuget restore semester_4/hometask_2_VS/hometask_2_VS.sln
  
build:
  project: semester_4/hometask_2_VS/hometask_2_VS.sln
  verbosity: minimal