image: Visual Studio 2017

branches:
  only:
    - s_2_homework_7_#2

environment:
  matrix:
    - project_name: semester_2/homework_7/Problem_2/Problem_2.csproj 

build_script:
  - dotnet run --project %project_name%
