image: Visual Studio 2017

branches:
  only:
    - s_4_hometask_5

before_build:
  - dotnet restore semester_4/hometask_5/hometask_5.sln

test_script:
  - dotnet test semester_4/hometask_5/hometask_5.sln

build:
  project: semester_4/hometask_5/hometask_5.sln